#!/usr/bin/env bash
#
# Build and launch the Sonolo Docker stack (PostgreSQL 16 + FastAPI API).
#
# Usage:
#   ./scripts/run_prod.sh
#
# First run generates a root .env with fresh POSTGRES_PASSWORD and
# SECRET_KEY values (gitignored). Delete .env to rotate credentials.
# See docs/RUNBOOK.md for the full variable reference.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker is required — https://docs.docker.com/get-docker/" >&2
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    echo "error: the 'docker compose' v2 plugin is required" >&2
    exit 1
fi

random_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    elif command -v python >/dev/null 2>&1; then
        python -c "import secrets; print(secrets.token_hex($1))"
    else
        echo "error: openssl or python is required to generate secrets" >&2
        exit 1
    fi
}

if [ ! -f .env ]; then
    echo "== No .env found — generating one with fresh credentials =="
    {
        echo "# Generated by scripts/run_prod.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')."
        echo "# Secrets live only in this gitignored file."
        echo "POSTGRES_USER=sonolo"
        echo "POSTGRES_PASSWORD=$(random_hex 16)"
        echo "POSTGRES_DB=sonolo"
        echo "SECRET_KEY=$(random_hex 32)"
        echo "ENVIRONMENT=production"
        echo "AI_MOCK_ENABLED=true"
    } > .env
    chmod 600 .env
else
    echo "== Using existing .env =="
fi

echo "== Building images =="
docker compose build

echo "== Starting stack =="
docker compose up -d

echo "== Running migrations =="
docker compose run --rm --no-deps api alembic upgrade head

echo "== Seeding content pack (idempotent) =="
docker compose run --rm --no-deps api python -m scripts.seed_content

echo "== Waiting for API health (up to 60s) =="
for _ in $(seq 1 30); do
    if docker compose exec -T api python -c "import sys,urllib.request; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/api/health', timeout=4).status == 200 else 1)" >/dev/null 2>&1; then
        echo "API healthy on http://localhost:${API_PORT:-8000}/api/health"
        docker compose ps
        exit 0
    fi
    sleep 2
done

echo "error: API did not become healthy within 60s — inspect 'docker compose logs api'" >&2
docker compose logs --tail 50 api >&2 || true
exit 1
